### ISSUE TITLE
Split DSL from actual binding

### ISSUE THREAD

**Issue by mrlem** [Doomsdayrs/kotlinx-gtk#3]
Hi there, thanks for this lib, nice job! I'm looking forward to seeing it get more complete :smiley: 

Reading your code, I was wondering whether you shouldn't split the actual binding from the DSL parts. This would allow users of your lib to import the DSL only if they use it.

===

Funny thing is I came across your project, having a primitive project of mine using GTK on kotlin native as well, but with a somewhat different approach.

While you chose the approach of creating full-blown kotlin classes to wrap the c pointers (which I'm convinced is the clean way to go), I chose a lighter & lazier approach to avoid wrapper objects: only use extensions, and no DSL but load the UI from a glade file. This has some limitations (especially not benefiting from component inheritance), but allows a reasonably simple code both in terms of bindng dev and user dev.

I guess the even more scaleable / sustainable approach would be to be able to use [GIR](https://gi.readthedocs.io/en/latest/) to generate the binding, but this seemed like even more work :wink: 

My code is definitely a lot less complete that yours, and I didn't deal with async'ing callbacks *at all*, but still. I thought you might want to have a look out of curiosity: https://github.com/mrlem/sample-kotlin-glade

**Comment by Doomsdayrs** [comment]
Unlike the assumption, the DSL is completely optional, and you can create the UIs using the native wrapper purely.

**Comment by Doomsdayrs** [comment]
I also do plan to add glade importing, where it can then get views out to be binded to. 

I just absolutely hate XML definition (coming from android dev)

**Comment by mrlem** [comment]
I'm also an android developer, so I completely get it. The DSL approach is really nice, though I tend to avoid putting logic in it (separation of concerns).

As for the "split DSL", I was thinking in terms of providing 2 distinct gradle dependencies. Then again, this might be overkill, as the lib is not too heavy.

**Comment by Doomsdayrs** [comment]
https://github.com/Doomsdayrs/kotlinx-gtk/blob/main/example/build.gradle.kts
Please take a look at the dependencies. They are split.

**Comment by mrlem** [comment]
I clearly missed it, sorry about that :pray: - guess I was a bit hasty reading the code with the end of the week.
I'll close the issue!
