### ISSUE TITLE
Could not compile on Fedora 34

### ISSUE THREAD

**Issue by sobotkami** [Doomsdayrs/kotlinx-gtk#4]
```
$ ./gradlew clean

BUILD SUCCESSFUL in 1s
18 actionable tasks: 4 executed, 14 up-to-date

$ ./gradlew example:assemble

> Task :nativex:compileKotlinNative FAILED
e: /home/mira/Dev/git/kotlinx-gtk/nativex/src/nativeMain/kotlin/nativex/gtk/cellrenderer/CellRenderer.kt: (37, 20): Unresolved reference: GTK_CELL_RENDERER_ACCEL_MODE_MODIFIER_TAP

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nativex:compileKotlinNative'.
> Compilation finished with errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
5 actionable tasks: 5 executed
```

In my system there is a Gtk of version 3.24.29-1.fc34. A searched the Gtk repository of this version but there is no GTK_CELL_RENDERER_ACCEL_MODE_MODIFIER_TAP.

**Comment by Doomsdayrs** [comment]
Thank you for your report @sobotkami, I will setup a KVM to try and replicate this behavior.

**Comment by Doomsdayrs** [comment]
It seems that `GTK_CELL_RENDERER_ACCEL_MODE_MODIFIER_TAP` doesn't exist past v3.24.25 or so.

I will setup fedora 34 and test to see what else has been removed.

**Comment by Doomsdayrs** [comment]
c5d3744 removes MODIFIER_TAP

**Comment by Doomsdayrs** [comment]
Well I had difficulties with the new environment. I hope the commit solves the issue for you

**Comment by sobotkami** [comment]
Thank you @Doomsdayrs for your response. Yes, the issue is gone.
