### ISSUE TITLE
[suggestion] Using the Compose Runtime to build the DSL.

### ISSUE THREAD

**Issue by Skaldebane** [Doomsdayrs/kotlinx-gtk#7]
Hi! I never used GTK before, and this project motivated me to try it once it's done. And as I see, you're going to create a DSL for all widgets to make creating them easier.

There I was wondering if you can use the Jetpack Compose Runtime (Multiplatform) to achieve this easily (and hence create a much better experience for the end-developer).

The only live example of the runtime so far is the Jetpack Compose UI toolkit.
This is just a suggestion that I doubt if it's useful at all, or if it even fits in the realm of GTK.

_Note: Compose UI shall not be confused with Compose Runtime. Although Google and Jetbrains use them interchangeably, the Compose Runtime is the lowest level of the Compose UI toolkit, and it can be used separately.

Another note: I'm no expert on any of this. I use Compose UI and so far it's the most enjoyable UI coding experience I've ever had, and I was wondering if it could be applied here._

**Comment by Doomsdayrs** [comment]
Currently this is out of the scope of the project as it is right now.

Even then, I have no idea how this would even be implemented, nor do I have any idea on where to start. 

If you wish to figure this out as a separate project, I'd be honored to see it happen. But I will not divert my current attention to the matter.

**Comment by Doomsdayrs** [comment]
Btw, It would be nice if you helped by choosing a class to wrap in Kotlin. The process is not too hard :D.

**Comment by Skaldebane** [comment]
Thanks for your reply!

I'll try to look into it deeply in my free time, then reply to you on how it goes.
