### ISSUE TITLE
Add binding progress to Wikipedia [suggestion]

### ISSUE THREAD

**Issue by Skaldebane** [Doomsdayrs/kotlinx-gtk#8]
You might want to add this binding to the following Wikipedia page:

[List of language bindings for GTK](https://en.wikipedia.org/wiki/List_of_language_bindings_for_GTK)

With the progress that you've done so far. It could be helpful if you add a GTK4 Column in there as well.

**Comment by Doomsdayrs** [comment]
Added to the list of bindings as of 08/09/2021 @ 20:21 EST
